# app.yaml

runtime: nodejs16
entrypoint: node index.js
env_variables:
  APP_NAME: "financial-analytics"
  NODE_ENV: "development"
  APP_KEY: "FFHyDNs5k6TKiAgQHjnIt8cDdW16_050"
  DRIVE_DISK: "local"
  DB_CONNECTION: "mysql"
  MYSQL_HOST: "analytics"
  MYSQL_PORT: 3306
  MYSQL_USER: "root"
  MYSQL_PASSWORD: ""
  MYSQL_DB_NAME: "financial-analytics"
  VFD_SECRET_KEY: "1ae441f0-89f0-3d9a-b954-9cad0fcb0f2f"
  VFD_API: "https://devesb.vfdbank.systems:8263/vfd-wallet/1.1/"
  VFD_CREDENTIALS: "eFZzS0F2a0NSbkNFMDJMb2t4VUx1VHprWUNrYTo5VHBFblJ3TVNlRUxoWlRvTk9WVzNNOXBfVElh"

