# .github/workflows/deploy.yaml

name: Deploy to Google App Engine
on:
  push:
    branches:
      - main
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: write to app yaml
        run: |-
          wget https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64.tar.gz -O - |\
          tar xz && sudo mv yq_linux_amd64 /usr/bin/yq
          echo ${{ secrets.STAGING_GAE_VARIABLES }} | base64 --decode > app.json && cat app.json | yq -P > /home/runner/work/analytics-349805/analytics-349805/app.yaml && rm app.json
          cat /home/runner/work/analytics-349805/analytics-349805/app.yaml
        
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          deliverables: 'app.yaml'