name: Staging-Deployment

on:
  push:
    branches: 
      - dev 
  pull_request:
    branches: 
       - dev 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: write to app yaml
      run: |-
        wget https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64.tar.gz -O - |\
        tar xz && sudo mv yq_linux_amd64 /usr/bin/yq
        echo ${{ secrets.GAE_VARIABLES }} | base64 --decode > app.json && cat app.json | yq -P > /home/runner/work/analytics-349805/analytics-349805/app.yaml && rm app.json
        cat /home/runner/work/analytics-349805/analytics-349805/app.yaml

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: 'Deploy to App Engine'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        deliverables: 'app.yaml'
        promote: true
        version: 'v1'
        flags: "--log-http --verbosity=debug"